# app.yaml
runtime: go113

handlers:
  # All other URLs are handled by the Go application.
  - url: /.*
    script: auto
env_variables:
  PORT: 8080
  FIREBASE_CREDENTIALS_FILE_PATH: "eguchi-wedding-firebase-adminsdk.json"
  FIREBASE_DATABASE_URL: "https://eguchi-wedding-default-rtdb.firebaseio.com"
  THINKING_TIME_SEC: 30
  CORS_ALLOW_ORIGINS: "https://quiz.hr20k.com"
includes:
  - secret.yaml
