name: Go-APP-deploy-to-GAE
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: GAE deploy
      run: |
        echo $EGUCHI_WEDDING_JSON > ./eguchi-wedding.json
        echo 'github-actions@eguchi-wedding.iam.gserviceaccount.com' | gcloud auth activate-service-account --key-file ./eguchi-wedding-firebase-adminsdk-t4euu-300ef2af8e.json
        gcloud app deploy --project eguchi-wedding ./app.yaml
      env:
        Go: true
