name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Install gcloud SDK
      run: |
        sudo apt-get update && sudo apt-get install google-cloud-sdk-app-engine-go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: GAE deploy
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
        Go: true
      run: |
        ./decrypt_secret.sh
        echo 'github-ations@eguchi-wedding.iam.gserviceaccount.com' | gcloud auth activate-service-account --key-file eguchi-wedding-google-app-engine-service-account.json
        gcloud app deploy --project eguchi-wedding ./app.yaml
