name: publish

on:
  workflow_dispatch:
    inputs:
      publish-version:
        description: 'junoのデプロイ用のバージョンを指定'
        required: true
        default: 'v0.1.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: checkout select git tag
        run: git checkout ${{ github.event.inputs.publish-version }}
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Run a script of started echo
        run: echo "Started publish target tag version."
      - name: echo publish tag
        run: |
          echo ${{ github.event.inputs.publish-version }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: GAE APP publish
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
        run: |
          ./decrypt_secret.sh
          gcloud app deploy --quiet ./app.yaml
      - name: Run a script of finished echo
        run: echo "Finished published target tag version."
